/*

 BACKGROUNDARRANGE.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : E:\gameboy\MazeGameGB\MazeGameGB\assets\BGGameTiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __BackgroundArrange_h_INCLUDE
#define __BackgroundArrange_h_INCLUDE

#define BaseBGWidth 20
#define BaseBGHeight 16
#define BaseBGBank 0

extern const unsigned char BaseBG[];

#endif

/* End of BACKGROUNDARRANGE.H */
