/*

 BLANKTILE.C

 Map Source File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 2 x 2
   Tile set      : D:\gameboy\MazeGameGB\MazeGameGB\BGGameTiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define BlankTileWidth 2
#define BlankTileHeight 2
#define BlankTileBank 0

unsigned char BlankTile[] =
{
  0x04,0x06,0x05,0x07
};

/* End of BLANKTILE.C */
