/*

 EXITTILE.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 2 x 2
   Tile set      : D:\gameboy\MazeGameGB\MazeGameGB\BGGameTiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define ExitTileWidth 2
#define ExitTileHeight 2
#define ExitTileBank 0

extern unsigned char ExitTile[];

/* End of EXITTILE.H */
