/*

 HUDMAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 4
   Tile set      : HudTiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 41
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __HudMap_h_INCLUDE
#define __HudMap_h_INCLUDE

#define HudMapLabelWidth 20
#define HudMapLabelHeight 4
#define HudMapLabelBank 0

extern const unsigned char HudMapLabel[];

#endif

/* End of HUDMAP.H */
