/*

 MAP1.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 16
   Tile set      : E:\gameboy\MazeGameGB\MazeGameGB\assets\BGGameTiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __Map1_h_INCLUDE
#define __Map1_h_INCLUDE

#define Map1LabelWidth 20
#define Map1LabelHeight 16
#define Map1LabelBank 0

extern const unsigned char Map1Label[];

#endif

/* End of MAP1.H */
