/*

 MAP3.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 16
   Tile set      : E:\gameboy\MazeGameGB\MazeGameGB\assets\BGGameTiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __Map3_h_INCLUDE
#define __Map3_h_INCLUDE

#define Map3LabelWidth 20
#define Map3LabelHeight 16
#define Map3LabelBank 0

extern const unsigned char Map3Label[];

#endif

/* End of MAP3.H */
