/*

 MAPBLAH.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 16
   Tile set      : E:\gameboy\MazeGameGB\MazeGameGB\assets\BGGameTiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __Mapblah_h_INCLUDE
#define __Mapblah_h_INCLUDE

#define MapblahLabelWidth 20
#define MapblahLabelHeight 16
#define MapblahLabelBank 0

extern const unsigned char MapblahLabel[];

#endif

/* End of MAPBLAH.H */
