/*

 BGGAMETILES.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 40

  Palette colors       : None.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : Yes.
  Index offset         : 0
  Index counter        : None.

 This file was generated by GBTD v2.2

*/


/* Bank of tiles. */
#define GameTilesBank 0
/* Metatile index */
extern unsigned char GameTilesIndex[];
/* Start of tile array. */
extern unsigned char GameTiles[];

/* End of BGGAMETILES.H */
