/*

 MAINSPRITETILES.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 16 x 16
  Tiles                : 1 to 10

  Palette colors       : None.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

#ifndef __MainSpriteTiles_h_INCLUDE
#define __MainSpriteTiles_h_INCLUDE

/* Bank of tiles. */
#define MainSpriteLabelBank 0
/* Start of tile array. */
extern const unsigned char MainSpriteLabel[];

#endif

/* End of MAINSPRITETILES.H */
